title: NUMECONCOPENHAGEN
urls: 
  - title: bla bla bla
    icon: bla
    url: bla
    weight: 10
index: 'content/index.md'
paths: 
  - content
  - content/guides
notebook:
  - title: Lectures
    notebooks:
      - url: https://....
        weight: 10
        title: bla bla bla