title: NUMECONCOPENHAGEN
urls: 
  groupTitle: false
  elements:
    - title: bla bla bla
      icon: bla
      url: bla
      weight: 10
    - title: bla bla bla
      icon: bla
      url: bla
      weight: 10
paths: 
  - content
  - content/guides
notebook:
  - title: Lectures
    notebooks:
      - url: https://....
        weight: 10
        title: bla bla bla